// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDnPAlgKDs_e4kR0KZ5t5oVihyLo5H6U3I',
    appId: '1:1085174797082:web:787d8a11cd8abc7c9112a3',
    messagingSenderId: '1085174797082',
    projectId: 'safespace-c696b',
    authDomain: 'safespace-c696b.firebaseapp.com',
    storageBucket: 'safespace-c696b.firebasestorage.app',
    measurementId: 'G-RQVZ5EKBJP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBrjjkG3-cpvyrCD5jvRe4y1xTr6-M0ntM',
    appId: '1:1085174797082:android:ec6f7c13d04810689112a3',
    messagingSenderId: '1085174797082',
    projectId: 'safespace-c696b',
    storageBucket: 'safespace-c696b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDO1BlfKj0h53MfWPvqIGrHe8ELzZAvfhA',
    appId: '1:1085174797082:ios:0d2859503adc9a1a9112a3',
    messagingSenderId: '1085174797082',
    projectId: 'safespace-c696b',
    storageBucket: 'safespace-c696b.firebasestorage.app',
    iosBundleId: 'com.example.safespace',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDO1BlfKj0h53MfWPvqIGrHe8ELzZAvfhA',
    appId: '1:1085174797082:ios:0d2859503adc9a1a9112a3',
    messagingSenderId: '1085174797082',
    projectId: 'safespace-c696b',
    storageBucket: 'safespace-c696b.firebasestorage.app',
    iosBundleId: 'com.example.safespace',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDnPAlgKDs_e4kR0KZ5t5oVihyLo5H6U3I',
    appId: '1:1085174797082:web:97458aca701afb1a9112a3',
    messagingSenderId: '1085174797082',
    projectId: 'safespace-c696b',
    authDomain: 'safespace-c696b.firebaseapp.com',
    storageBucket: 'safespace-c696b.firebasestorage.app',
    measurementId: 'G-EVEQNB6T2S',
  );
}
